### PR TITLE
Align billboard to Y axis

### PR DESCRIPTION
**Pull request by qqii**

### CODE REVIEW

**Comment by AnthonyWharton** [comment]
Does it all work? Can I get someone else testing it as I'm out of office so to speak...

**Comment by Codrin-Popa** [comment]
Will push a commit in a few minutes

**Comment by Codrin-Popa** [comment]
It's working as expected. Builds and runs on linux

**Comment by AnthonyWharton** [comment]
Good to be approved?

**Comment by Codrin-Popa** [comment]
yes

**Pull request merged**
