### PR TITLE
Fix: Silly Attack System Sync bugs

### PR DESCRIPTION
**Pull request by AnthonyWharton**
- And fixed ComponentAttack.isAttacking()

**Feel free to delete this branch once merged.**

### CODE REVIEW

**Comment by RcColes** [comment]
Oh fuck

**Comment by RcColes** [comment]
Sorry Jamie, I've just done exactly the same thing

**Comment by AnthonyWharton** [comment]
What a hypocrit.. #smh

**Comment by RcColes** [comment]
Yeah I know

**Comment by RcColes** [comment]
I forget that PRs that aren't matter go into here as well

**Pull request merged**
