### PR TITLE
aw/disconnect

### PR DESCRIPTION
**Pull request by AnthonyWharton**
It's hacky and it doesn't deallocate graphics things properly when people disconnect, so it slowly memory leaks and thus seg-faults on closing if something disconnected during runtime.. But other than that it's great :stuck_out_tongue:

### CODE REVIEW

**Comment by AnthonyWharton** [comment]
If anyone from Graphics has any smart ideas on how to deallocate things @grant-m-s @Codrin-Popa @jnterry @qqii that would be great

**Comment by grant-m-s** [comment]
so why would we ever think of accepting this?

**Comment by AnthonyWharton** [comment]
Because it works and apparently "we want a working game instead of a perfect one" :wink: 
 - @RcColes 2017, 2018

**Comment by grant-m-s** [comment]
but what _works_ about it?

**Comment by AnthonyWharton** [comment]
Things disconnect innit

**Comment by RcColes** [comment]
Good news Grant, we can accept this now

**Comment by AnthonyWharton** [comment]
👍

**Comment by grant-m-s** [comment]
image

**Pull request merged**
