### PR TITLE
Cp/windows crash bug fix

### PR DESCRIPTION
**Pull request by grant-m-s**
Fix for windows crash and HUGE amounts of printing when an entity wonders off the level

### CODE REVIEW

**Comment by AnthonyWharton** [comment]
I appear to stand corrected, `existsTile()` checks if tile heights are greater than 0. Can you confirm that 0 is the minimum/NULL/no tile height?

**Comment by grant-m-s** [comment]
we should use NO_TILE

**Comment by AnthonyWharton** [comment]
Is that already a thing? If so where?

**Comment by grant-m-s** [comment]
edited comment ^

**Comment by grant-m-s** [comment]
we use it when we create the level and the bitmap pixel value is black

**Pull request merged**
