### PR TITLE
Add Respawn Mechanic & Minor Combo Enhancements

### PR DESCRIPTION
**Pull request by AnthonyWharton**
Combo enhancements include, zeroing combo on death, and breaking combo when colliding into a wall/enemy.

### CODE REVIEW

**Comment by AnthonyWharton** [comment]
Fixed. Paging @RcColes @qqii @grant-m-s @jnterry @Codrin-Popa

**Comment by AnthonyWharton** [comment]
Good point about the level - And damn, I guess I was a bit hasty in the loosing combo thing. I'll sort it in the morning. Thanks!

**Comment by qqii** [comment]
@jnterry

> Why are we including the hacked level with the "cheat" paths in a merge to master?

Without a better level loader or a better set of tests this is the easiest way to explore the level while in development.

**Comment by AnthonyWharton** [comment]
Oh bugger, alright - easy fix.

**Pull request merged**
