### PR TITLE
Cp/healing

### PR DESCRIPTION
**Pull request by Codrin-Popa**
Health automatically heals over time while having a combo over 20.
Added particle system for healing.

### CODE REVIEW

**Comment by Codrin-Popa** [comment]
I removed some things that are no longer needed. It should work on Windows now.

**Comment by grant-m-s** [comment]
Yep it works now, not sure if the health is increasing a little quickly though, we'll have to test it abit more (it might be fine for bosses

**Comment by AnthonyWharton** [comment]
Looks like you need to merge in the new master safely before this can be merged @Codrin-Popa

**Comment by Codrin-Popa** [comment]
Regarding healing too fast: We could increase the default health to a bigger number, make health a float or I could increase the health every other beat.
At the moment I am increasing the health by 1 every beat.

**Comment by AnthonyWharton** [comment]
Ahh yes ok, I think every beat or two is the best option for now - lots of things will break if we change it to a float now. Changing max health could work but will require looking at all the enemies.

**Pull request merged**
