### PR TITLE
Rc/real music

### PR DESCRIPTION
**Pull request by RcColes**
Actually very playable now, able to get 150ish combo where before I was just being really bad. Only problem is that the music doesn't loop, so we've only got a minute and a half

### CODE REVIEW

**Comment by RcColes** [comment]
This needs testing on some other systems, as the sound sync might only work on my setup (due to latency etc)

**Comment by grant-m-s** [comment]
Might just be me being bad, but roughly the first half of the song I can barely above 10 combo. The second half seems so much easier (can easily get 100)... not sure if its the way the song is, the crude loop slightly off? or something else. @RcColes noticed anything similar?

**Comment by Codrin-Popa** [comment]
In some portions of the song it's trickier to feel the beat because there's other stuff at a higher volume.

**Comment by AnthonyWharton** [comment]
We're working on it @grant-m-s @Codrin-Popa, basically we've now hit underlying problem of computers having audio playback latency, regardless of what you use.. And this is not measurable so we're having fun solving this one 👍

**Comment by RcColes** [comment]
Right, try it now. I've switched to playing it on the server and it looks like the latency is okay there. In future we may need some sort of calibration tool for this

**Comment by grant-m-s** [comment]
@RcColes Definitely better but now (on Windows atleast) it takes 30 seconds for the server window to do anything.

**Comment by RcColes** [comment]
That's the load time for the track, as it's pretty big. In the past, a transcode to .ogg fucked the sync, but I'll try it again

**Comment by grant-m-s** [comment]
@AnthonyWharton might beat you to it there

**Comment by RcColes** [comment]
Cool that seems fine

**Comment by RcColes** [comment]
More testing would be appreciated, but I think we're nearly there now

**Pull request merged**
