### PR TITLE
Players move back to spawnpoint on death

### PR DESCRIPTION
**Pull request by RcColes**
Quick change so that death is less painful. Currently camera position doesn't quite update properly, but I'm not sure why

### CODE REVIEW

**Comment by RcColes** [comment]
We'll need this for the demo day, and it's also nice to have

**Comment by grant-m-s** [comment]
this will be changed slightly i think because feeder_areas will affect spawn locations

**Comment by RcColes** [comment]
Is that going to be ready for tomorrow?

**Comment by grant-m-s** [comment]
absolutely its practically finished

**Pull request merged**
